In [2]:
import numpy as np #here np is an alias used as a shortcut name to call numpy

In [4]:
# TO CREATE AN ARRAY.
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [5]:
# WAY TO SEARCH WHICH TYPE OF AN ARRAY IT IS
type(a)

numpy.ndarray

### BASIC OPERATIONS OF AN ARRAY.


In [6]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


#### CREATING MORE THAN 1-D ARRAY

In [7]:
# Creating 2-D Array.
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(a2.shape) # This method tells the shape of an array and it tells the no. of rows and no. of columns,

(2, 3)


In [11]:
# To search the dimension of an array,
print(a2.ndim) # here ndim is no of dimensions,

2


In [15]:
# Method to generate range,
np.arange(1,11,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
array=np.random.randint(1,11, size=(3,4))
print(array)

[[3 5 3 4]
 [4 1 2 2]
 [6 4 7 4]]


In [20]:
x= np.array([[7,2,3],
            [3,9,4],
            [3,4,5]])

y= np.array([[3,4,5],
             [3,9,4],
             [7,2,3]])

print(x)
print(y)

[[7 2 3]
 [3 9 4]
 [3 4 5]]
[[3 4 5]
 [3 9 4]
 [7 2 3]]


In [23]:
print(x@y) #Matrix Multiplication

[[ 48  52  52]
 [ 64 101  63]
 [ 56  58  46]]


In [24]:
# Another way of matrix multiplication
np.dot(x,y)

array([[ 48,  52,  52],
       [ 64, 101,  63],
       [ 56,  58,  46]])

In [25]:
x.prod() #Product of all elements overall

np.int64(272160)

### METHODS FOR BASIC STATISTICS

In [26]:
x.mean()

np.float64(4.444444444444445)

In [27]:
y.mean()

np.float64(4.444444444444445)